USE MASTER
GO

IF DB_ID ('BD_DSWI') IS NOT NULL 
 	BEGIN 
 	 	ALTER DATABASE BD_DSWI
		SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		DROP DATABASE BD_DSWI
 	END 
GO

CREATE DATABASE BD_DSWI
COLLATE MODERN_SPANISH_CI_AI
GO

USE BD_DSWI
GO

SET LANGUAGE SPANISH
GO

SET DATEFORMAT DMY
GO

IF OBJECT_ID ('TBDISTRITO','U') IS NOT NULL
	BEGIN
		DROP TABLE TBDISTRITO
	END
GO
CREATE TABLE TBDISTRITO(
	CODDIS CHAR(5) PRIMARY KEY,
	NOMDIS VARCHAR(50)
)
GO


IF OBJECT_ID ('TBCARGO','U') IS NOT NULL
	BEGIN
		DROP TABLE TBCARGO
	END
GO
CREATE TABLE TBCARGO(
CODCARGO CHAR(5) PRIMARY KEY,
NOMCARGO VARCHAR(50)
)
GO

IF OBJECT_ID ('TBEMPLEADOS','U') IS NOT NULL
	BEGIN
		DROP TABLE TBEMPLEADOS
	END
GO
CREATE TABLE TBEMPLEADOS(
	CODEMP CHAR(5) PRIMARY KEY,
	NOMEMP VARCHAR(50),
	CODDIS CHAR(5) FOREIGN KEY REFERENCES TBDISTRITO(CODDIS),
	DIRECCION VARCHAR(50),
	DNI CHAR(8),
	EMAIL VARCHAR(50),
	TURNO CHAR(1) CHECK (TURNO IN ('M','N')),
	CELULAR CHAR(9),
	FEC_ING DATE,
	CODCARGO CHAR(5) FOREIGN KEY REFERENCES TBCARGO(CODCARGO),
	CONTRA VARCHAR(25),
	ELIMINADO CHAR(2) DEFAULT 'NO'
	
)
GO

SELECT 'BASE DE DATOS BD_DSWI CREADA CORRECTAMENTE' AS MENSAJE
GO
