USE BD_DSWI
GO

INSERT INTO TBDISTRITO VALUES('DIS01','ATE')
INSERT INTO TBDISTRITO VALUES('DIS02','BARRANCO')
INSERT INTO TBDISTRITO VALUES('DIS03','BREÑA')
INSERT INTO TBDISTRITO VALUES('DIS04','CALLAO')
INSERT INTO TBDISTRITO VALUES('DIS05','CERCADO DE LIMA')
INSERT INTO TBDISTRITO VALUES('DIS06','CHORRILLOS')
INSERT INTO TBDISTRITO VALUES('DIS07','COMAS')
INSERT INTO TBDISTRITO VALUES('DIS08','EL AGUSTINO')
INSERT INTO TBDISTRITO VALUES('DIS09','INDEPENDENCIA')
INSERT INTO TBDISTRITO VALUES('DIS10','JESÚS MARÍA')
INSERT INTO TBDISTRITO VALUES('DIS11','LA MOLINA')
INSERT INTO TBDISTRITO VALUES('DIS12','LA VICTORIA')
INSERT INTO TBDISTRITO VALUES('DIS13','LINCE')
INSERT INTO TBDISTRITO VALUES('DIS14','MAGDALENA DEL MAR')
INSERT INTO TBDISTRITO VALUES('DIS15','MIRAFLORES')
INSERT INTO TBDISTRITO VALUES('DIS16','PUEBLO LIBRE')
INSERT INTO TBDISTRITO VALUES('DIS17','PUENTE PIEDRA')
INSERT INTO TBDISTRITO VALUES('DIS18','RÍMAC')
INSERT INTO TBDISTRITO VALUES('DIS19','SAN BORJA')
INSERT INTO TBDISTRITO VALUES('DIS20','SAN ISIDRO')
INSERT INTO TBDISTRITO VALUES('DIS21','SAN JUAN DE LURIGANCHO')
INSERT INTO TBDISTRITO VALUES('DIS22','SAN JUAN DE MIRAFLORES')
INSERT INTO TBDISTRITO VALUES('DIS23','SAN LUIS')
INSERT INTO TBDISTRITO VALUES('DIS24','SAN MARTÍN DE PORRES')
INSERT INTO TBDISTRITO VALUES('DIS25','SAN MIGUEL')
INSERT INTO TBDISTRITO VALUES('DIS26','SANTA ANITA')
INSERT INTO TBDISTRITO VALUES('DIS27','SANTA ROSA')
INSERT INTO TBDISTRITO VALUES('DIS28','SANTIAGO DE SURCO')
INSERT INTO TBDISTRITO VALUES('DIS29','SURQUILLO')
INSERT INTO TBDISTRITO VALUES('DIS30','VENTANILLA')
INSERT INTO TBDISTRITO VALUES('DIS31','VILLA EL SALVADOR')
INSERT INTO TBDISTRITO VALUES('DIS32','VILLA MARIA DEL TRIUNFO')
INSERT INTO TBDISTRITO VALUES('DIS33','VENTANILLA')
GO
 
 --********************************************************************************

 
INSERT INTO TBCARGO VALUES ('CAR01','PASTELERO(A)')
INSERT INTO TBCARGO VALUES ('CAR02','PANADERO(A)')
INSERT INTO TBCARGO VALUES ('CAR03','AYUDANTE')
INSERT INTO TBCARGO VALUES ('CAR04','VENDEDOR(A)')
INSERT INTO TBCARGO VALUES ('CAR05','CAJERO(A)')
INSERT INTO TBCARGO VALUES ('CAR06','TRANSPORTISTA')
GO

--************************************************************************************

select * from TBDISTRITO
go

select * from TBCARGO
go

select * from TBEMPLEADOS
go

INSERT INTO TBEMPLEADOS (CODEMP,NOMEMP,CODDIS,DIRECCION,DNI,EMAIL,TURNO,CELULAR,FEC_ING,CODCARGO) 
VALUES ('E0005','JOSE GALLARDO JOAQUIN','DIS03','CALLE FALSA N° 124','40064400','jose_uno2014@hotmail.com','N','822714239',SYSDATETIME(),'CAR01')
GO

