USE BD_DSWI
GO
/************************************ COMBOBOX ************************************/
/****************** DISTRITO ******************/
IF OBJECT_ID('USP_LISTAR_DISTRITOS','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_DISTRITOS
GO
CREATE PROCEDURE USP_LISTAR_DISTRITOS
AS
	SELECT D.CODDIS,D.NOMDIS
	FROM TBDISTRITO D
GO
/****************** DISTRITO ******************/

/****************** CARGO ******************/
IF OBJECT_ID('USP_LISTAR_CARGOS','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_CARGOS
GO
CREATE PROCEDURE USP_LISTAR_CARGOS
AS
	SELECT C.CODCARGO,C.NOMCARGO
	FROM TBCARGO C
GO
/****************** CARGO ******************/

/****************** TIPO ******************/
IF OBJECT_ID('USP_LISTAR_TIPOS','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_TIPOS
GO
CREATE PROCEDURE USP_LISTAR_TIPOS
AS
	SELECT T.CODTIPO,T.DESCRIPCION
	FROM TBTIPO T
GO
/****************** TIPO ******************/
/************************************ COMBOBOX ************************************/

/************************************ MANTENIMIENTOS ************************************/
/****************** PRODUCTOS ******************/

IF OBJECT_ID('USP_LISTAR_PRODUCTOS','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_PRODUCTOS
GO
CREATE PROCEDURE USP_LISTAR_PRODUCTOS
AS
	SELECT P.CODPRO,P.NOMPRO,P.STOCK,P.PRECIO,T.DESCRIPCION,P.ELIMINADO
	FROM TBPRODUCTO P INNER JOIN TBTIPO T
		ON P.CODTIPO = T.CODTIPO
GO

IF OBJECT_ID('USP_LISTAR_PRODUCTOS_X_DESCRIPCION','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_PRODUCTOS_X_DESCRIPCION
GO
CREATE PROCEDURE USP_LISTAR_PRODUCTOS_X_DESCRIPCION
@XCODTIPO CHAR(5)
AS
	SELECT P.CODPRO,P.NOMPRO,P.STOCK,P.PRECIO,T.DESCRIPCION,P.ELIMINADO
	FROM TBPRODUCTO P INNER JOIN TBTIPO T
		ON P.CODTIPO = T.CODTIPO
	WHERE P.CODTIPO = @XCODTIPO /* TIP01 - TIP02 - TIP03 */
GO

IF OBJECT_ID('USP_INSERTAR_PRODUCTOS','P') IS NOT NULL
	DROP PROCEDURE USP_INSERTAR_PRODUCTOS
GO
CREATE PROCEDURE USP_INSERTAR_PRODUCTOS
@XCODPRO CHAR(5),@XNOMPRO VARCHAR(250),@XSTOCK INT,@XPRECIO MONEY,
@XCODTIPO CHAR(5),@XELIMINADO CHAR(2)
AS
	INSERT INTO TBPRODUCTO VALUES(@XCODPRO,@XNOMPRO,@XSTOCK,@XPRECIO,@XCODTIPO,@XELIMINADO)
GO

IF OBJECT_ID('USP_ACTUALIZAR_PRODUCTOS','P') IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_PRODUCTOS
GO
CREATE PROCEDURE USP_ACTUALIZAR_PRODUCTOS
@XCODPRO CHAR(5),@XNOMPRO VARCHAR(250),@XSTOCK INT,@XPRECIO MONEY,
@XCODTIPO CHAR(5),@XELIMINADO CHAR(2)
AS
	UPDATE TBPRODUCTO
	SET NOMPRO = @XNOMPRO,
		STOCK = @XSTOCK,
		PRECIO = @XPRECIO,
		CODTIPO = @XCODTIPO,
		ELIMINADO = @XELIMINADO
	WHERE CODPRO = @XCODPRO
GO


IF OBJECT_ID('USP_ELIMINAR_PRODUCTOS_BD','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_PRODUCTOS_BD
GO
CREATE PROCEDURE USP_ELIMINAR_PRODUCTOS_BD
@XCODPRO CHAR(5)
AS
	DELETE FROM TBPRODUCTO
	WHERE CODPRO = @XCODPRO
GO

IF OBJECT_ID('USP_ELIMINAR_PRODUCTOS_LOGIC','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_PRODUCTOS_LOGIC
GO
CREATE PROCEDURE USP_ELIMINAR_PRODUCTOS_LOGIC
@XCODPRO CHAR(5)
AS
	UPDATE TBPRODUCTO
	SET ELIMINADO = 'SI'
	WHERE CODPRO = @XCODPRO
GO


/****************** PRODUCTOS ******************/

/****************** CLIENTES ******************/
IF OBJECT_ID('USP_LISTAR_CLIENTES','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_CLIENTES
GO
CREATE PROCEDURE USP_LISTAR_CLIENTES
AS
	SELECT C.CODCLI,C.NOMCLI,D.NOMDIS,C.DIRECCION,C.DNI,C.EMAIL,C.CELULAR,C.ELIMINADO
	FROM TBCLIENTES C INNER JOIN TBDISTRITO D
		ON C.CODDIS = D.CODDIS
GO

IF OBJECT_ID('USP_LISTAR_CLIENTES_X_DISTRITO','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_CLIENTES_X_DISTRITO
GO
CREATE PROCEDURE USP_LISTAR_CLIENTES_X_DISTRITO
@XCODDIS CHAR(5)
AS
	SELECT C.CODCLI,C.NOMCLI,D.NOMDIS,C.DIRECCION,C.DNI,C.EMAIL,C.CELULAR,C.ELIMINADO
	FROM TBCLIENTES C INNER JOIN TBDISTRITO D
		ON C.CODDIS = D.CODDIS
	WHERE C.CODDIS = @XCODDIS
GO

IF OBJECT_ID('USP_INSERTAR_CLIENTES','P') IS NOT NULL
	DROP PROCEDURE USP_INSERTAR_CLIENTES
GO
CREATE PROCEDURE USP_INSERTAR_CLIENTES
@XCODCLI CHAR(5),@XNOMCLI VARCHAR(50),@XCODDIS CHAR(5),
@XDIRECCION VARCHAR(50),@XDNI CHAR(8),@XEMAIL VARCHAR(50),
@XCELULAR CHAR(9)
AS
	INSERT INTO TBCLIENTES(CODCLI,NOMCLI,CODDIS,DIRECCION,DNI,EMAIL,CELULAR)
	 VALUES (@XCODCLI,@XNOMCLI,@XCODDIS,@XDIRECCION,@XDNI,@XEMAIL,@XCELULAR)
GO

IF OBJECT_ID('USP_ACTUALIZAR_CLIENTES','P') IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_CLIENTES
GO
CREATE PROCEDURE USP_ACTUALIZAR_CLIENTES
@XCODCLI CHAR(5),@XNOMCLI VARCHAR(50),@XCODDIS CHAR(5),
@XDIRECCION VARCHAR(50),@XDNI CHAR(8),@XEMAIL VARCHAR(50),
@XCELULAR CHAR(9),@XELIMINADO CHAR(2)
AS
	UPDATE TBCLIENTES
	SET NOMCLI = @XNOMCLI,
		CODDIS = @XCODDIS,
		DIRECCION = @XDIRECCION,
		DNI = @XDNI,
		EMAIL = @XEMAIL,
		CELULAR = @XCELULAR,
		ELIMINADO = @XELIMINADO
	WHERE CODCLI = @XCODCLI
GO

IF OBJECT_ID('USP_ELIMINAR_CLIENTES_BD','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_CLIENTES_BD
GO
CREATE PROCEDURE USP_ELIMINAR_CLIENTES_BD
@XCODCLI CHAR(5)
AS
	DELETE FROM TBCLIENTES
	WHERE CODCLI = @XCODCLI
GO

IF OBJECT_ID('USP_ELIMINAR_CLIENTES_LOGIC','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_CLIENTES_LOGIC
GO
CREATE PROCEDURE USP_ELIMINAR_CLIENTES_LOGIC
@XCODCLI CHAR(5)
AS
	UPDATE TBCLIENTES
	SET ELIMINADO = 'SI'
	WHERE CODCLI = @XCODCLI
GO

/****************** CLIENTES ******************/

/****************** EMPLEADOS ******************/
IF OBJECT_ID('USP_LISTAR_EMPLEADOS','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_EMPLEADOS
GO
CREATE PROCEDURE USP_LISTAR_EMPLEADOS
AS
	SELECT E.CODEMP,E.NOMEMP,D.NOMDIS,E.DIRECCION,E.DNI,E.TURNO,E.CELULAR,E.FEC_ING,C.NOMCARGO,E.ELIMINADO
	FROM TBEMPLEADOS E INNER JOIN TBDISTRITO D
		ON E.CODDIS = D.CODDIS INNER JOIN TBCARGO C
			ON E.CODCARGO = C.CODCARGO
GO

IF OBJECT_ID('USP_LISTAR_EMPLEADOS_X_DISTRITO','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_EMPLEADOS_X_DISTRITO
GO
CREATE PROCEDURE USP_LISTAR_EMPLEADOS_X_DISTRITO
@XCODDIS CHAR(5)
AS
	SELECT E.CODEMP,E.NOMEMP,D.NOMDIS,E.DIRECCION,E.DNI,E.TURNO,E.CELULAR,E.FEC_ING,C.NOMCARGO,E.ELIMINADO
	FROM TBEMPLEADOS E INNER JOIN TBDISTRITO D
		ON E.CODDIS = D.CODDIS INNER JOIN TBCARGO C
			ON E.CODCARGO = C.CODCARGO
	WHERE E.CODDIS = @XCODDIS
GO

IF OBJECT_ID('USP_LISTAR_EMPLEADOS_X_CARGO','P') IS NOT NULL
	DROP PROCEDURE USP_LISTAR_EMPLEADOS_X_CARGO
GO
CREATE PROCEDURE USP_LISTAR_EMPLEADOS_X_CARGO
@XCODCARGO CHAR(5)
AS
	SELECT E.CODEMP,E.NOMEMP,D.NOMDIS,E.DIRECCION,E.DNI,E.TURNO,E.CELULAR,E.FEC_ING,C.NOMCARGO,E.ELIMINADO
	FROM TBEMPLEADOS E INNER JOIN TBDISTRITO D
		ON E.CODDIS = D.CODDIS INNER JOIN TBCARGO C
			ON E.CODCARGO = C.CODCARGO
	WHERE E.CODCARGO = @XCODCARGO
GO

IF OBJECT_ID('USP_INSERTAR_EMPLEADOS','P') IS NOT NULL
	DROP PROCEDURE USP_INSERTAR_EMPLEADOS
GO
CREATE PROCEDURE USP_INSERTAR_EMPLEADOS
@XCODEMP CHAR(5),@XNOMEMP VARCHAR(50),@XCODDIS CHAR(5),@XDIRECCION VARCHAR(50),
@XDNI CHAR(8),@XTURNO CHAR(1),@XCELULAR CHAR(9),@XFEC_ING DATE,@XCODCARGO CHAR(5)
AS
	INSERT INTO TBEMPLEADOS(CODEMP,NOMEMP,CODDIS,DIRECCION,DNI,TURNO,CELULAR,FEC_ING,CODCARGO)
	 VALUES (@XCODEMP,@XNOMEMP,@XCODDIS,@XDIRECCION,@XDNI,@XTURNO,@XCELULAR,
									@XFEC_ING,@XCODCARGO)
GO

IF OBJECT_ID('USP_ACTUALIZAR_EMPLEADOS','P') IS NOT NULL
	DROP PROCEDURE USP_ACTUALIZAR_EMPLEADOS
GO
CREATE PROCEDURE USP_ACTUALIZAR_EMPLEADOS
@XCODEMP CHAR(5),@XNOMEMP VARCHAR(50),@XCODDIS CHAR(5),@XDIRECCION VARCHAR(50),
@XDNI CHAR(8),@XTURNO CHAR(1),@XCELULAR CHAR(9),@XFEC_ING DATE,@XCODCARGO CHAR(5),
@XELIMINADO CHAR(2)
AS
	UPDATE TBEMPLEADOS
	SET NOMEMP = @XNOMEMP,
		CODDIS = @XCODDIS,
		DIRECCION = @XDIRECCION,
		DNI = @XDNI,
		TURNO = @XTURNO,
		CELULAR = @XCELULAR,
		FEC_ING = @XFEC_ING,
		CODCARGO = @XCODCARGO,
		ELIMINADO = @XELIMINADO
	WHERE CODEMP = @XCODEMP
GO

IF OBJECT_ID('USP_ELIMINAR_EMPLEADOS_BD','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_EMPLEADOS_BD
GO
CREATE PROCEDURE USP_ELIMINAR_EMPLEADOS_BD
@XCODEMP CHAR(5)
AS
	DELETE FROM TBEMPLEADOS
	WHERE CODEMP = @XCODEMP
GO

IF OBJECT_ID('USP_ELIMINAR_EMPLEADOS_LOGIC','P') IS NOT NULL
	DROP PROCEDURE USP_ELIMINAR_EMPLEADOS_LOGIC
GO
CREATE PROCEDURE USP_ELIMINAR_EMPLEADOS_LOGIC
@XCODEMP CHAR(5)
AS
	UPDATE TBEMPLEADOS
	SET ELIMINADO = 'SI'
	WHERE CODEMP = @XCODEMP
GO
/****************** EMPLEADOS ******************/

/************************************ MANTENIMIENTOS ************************************/



/******************  ******************/
/******************  ******************/
/******************  ******************/
/******************  ******************/
/******************  ******************/
/******************  ******************/
/******************  ******************/
/******************  ******************/

SELECT 'PROCEDIMIENTOS ALMACENADOS CREADOS CON EXITO' AS MENSAJE
GO