USE BD_DSWI
GO

CREATE TRIGGER TG_GENERA_CONTRAS_CLIENTE
ON TBCLIENTES
AFTER  INSERT
AS 
BEGIN 
DECLARE @NOM CHAR(4)
DECLARE @DNI CHAR(4)
DECLARE @ID CHAR(5)

	SELECT @NOM=SUBSTRING(inserted.NOMCLI,0,5),@DNI=SUBSTRING(inserted.DNI,0,5), @ID=inserted.CODCLI FROM inserted
	UPDATE TBCLIENTES SET TBCLIENTES.CONTRA=CONCAT(@NOM,@DNI)
	WHERE TBCLIENTES.CODCLI=@ID
END
GO

CREATE TRIGGER TG_GENERA_CONTRAS_EMPLEADO
ON TBEMPLEADOS
AFTER  INSERT
AS 
BEGIN 
DECLARE @NOM CHAR(4)
DECLARE @DNI CHAR(4)
DECLARE @ID CHAR(5)

	SELECT @NOM=SUBSTRING(inserted.NOMEMP,0,5),@DNI=SUBSTRING(inserted.DNI,0,5), @ID=inserted.CODEMP FROM inserted
	UPDATE TBEMPLEADOS SET TBEMPLEADOS.CONTRA=CONCAT(@NOM,@DNI)
	WHERE TBEMPLEADOS.CODEMP=@ID
END
GO